#!/bin/sh                                                                                                                          

# |gco|: compile |@program@.c| [...] , 'outputting' to basename of first arg.                                                      

# written by Hugh McGuire                                                                                                          

if [ $# -lt 1 ]
then
    echo Usage:\  `basename $0` '@program@.c' '[...]' >&2
    exit 1
fi

DIRNAME=`dirname "$1"`
BASENAME=`basename "$1" .c`

if [ "${BASENAME}.c" != `basename "$1"` ]
then
    echo Usage:\  `basename $0` '@program@.c' '[...]' >&2
    exit 1
fi

# if debugging:                                                                                                                    
set -x                  # seems nice even if not debugging                                                                         
# set -v                                                                                                                           

gcc -std=c99 -Wall -g "$@" -lm -lpthread -lncurses -lGL -lGLU -lglut -o "$DIRNAME/$BASENAME"
./$BASENAME


